### ISSUE TITLE
Question: Is RPI 4 supported?

### ISSUE THREAD

**Issue by ZGStuff** [cilynx/outfox-raspi-installer#3]
I'm hoping to get OutFox running on my Pi 4 4GB, since I'm a bit of a fan of rhythm games. Will it work?????? Can test if needed

**Comment by cilynx** [comment]
The script as-is should work and at least launch Outfox on any 64-bit Pi -- RasPi 3 or new, running 64-bit OS.  I've heard of other folks running Outfox without substantial performance issues on a RasPi 4, so I think there's a good chance it will work well for you.  Give it a shot and let us know how it goes.

**Comment by ZGStuff** [comment]
alright! gonna do that lol

**Comment by cilynx** [comment]
How'd it work for you on the Pi 4?  If it's working well for you, I'd like to add the 4 to the tested list in the README.

**Comment by ZGStuff** [comment]
still workin on it lol
havent had time
